-- Financial Report Header Print Format - Portrait & Landscape
-- Sep 30, 2019 11:47:56 AM IST
INSERT INTO AD_PrintFormat (Updated,CreatedBy,IsTableBased,IsActive,IsStandardHeaderFooter,AD_PrintFont_ID,AD_Table_ID,IsForm,HeaderMargin,UpdatedBy,AD_PrintColor_ID,Created,Name,CreateCopy,FooterMargin,AD_Client_ID,AD_PrintPaper_ID,AD_Org_ID,AD_PrintFormat_ID,AD_PrintTableFormat_ID,IsDefault,AD_PrintFormat_UU,RecordLimit) VALUES (TO_TIMESTAMP('2019-09-30 11:47:56','YYYY-MM-DD HH24:MI:SS'),100,'Y','Y','N',164,282,'Y',80,100,100,TO_TIMESTAMP('2019-09-30 11:47:56','YYYY-MM-DD HH24:MI:SS'),'Financial Report Header - Portrait','N',0,0,103,0,200011,100,'N','fcf86d39-a182-4a0c-b012-96cf4e7f63d3',0)
;

-- Sep 30, 2019 11:52:30 AM IST
INSERT INTO AD_Column (AD_Column_ID,Version,Name,AD_Table_ID,ColumnName,FieldLength,IsKey,IsParent,IsMandatory,IsTranslated,IsIdentifier,SeqNo,IsEncrypted,AD_Reference_ID,AD_Client_ID,AD_Org_ID,IsActive,Created,CreatedBy,Updated,UpdatedBy,AD_Element_ID,IsUpdateable,IsSelectionColumn,EntityType,IsSyncDatabase,IsAlwaysUpdateable,ColumnSQL,IsAutocomplete,IsAllowLogging,AD_Column_UU,IsAllowCopy,SeqNoSelection,IsToolbarButton,IsSecure) VALUES (214057,0,'Logo',282,'Logo_ID',10,'N','N','N','N','N',0,'N',32,0,0,'Y',TO_TIMESTAMP('2019-09-30 11:52:29','YYYY-MM-DD HH24:MI:SS'),100,TO_TIMESTAMP('2019-09-30 11:52:29','YYYY-MM-DD HH24:MI:SS'),100,53909,'N','N','D','N','N','(SELECT NVL(oi.Logo_ID, ci.LogoReport_ID) AS Logo_ID FROM AD_PInstance p INNER JOIN AD_ClientInfo ci ON (ci.AD_Client_ID = p.AD_Client_ID AND p.AD_PInstance_ID = AD_PInstance.AD_PInstance_ID) LEFT JOIN AD_PInstance_Para pp ON (pp.AD_PInstance_ID = p.AD_PInstance_ID AND pp.ParameterName ILIKE ''Org_ID'' AND pp.P_Number > 0) LEFT JOIN AD_OrgInfo oi ON (oi.AD_Org_ID = pp.P_Number))','N','Y','5e9c2336-0a24-4330-9033-fb083f616b7a','N',0,'N','N')
;

-- Sep 30, 2019 11:54:40 AM IST
INSERT INTO AD_PrintFormatItem (SeqNo,Name,Created,IsNextLine,AD_Client_ID,YSpace,SortNo,AD_Column_ID,IsPageBreak,IsRelativePosition,UpdatedBy,MaxWidth,AD_PrintFormatItem_ID,CreatedBy,IsSummarized,YPosition,AD_PrintColor_ID,Updated,AD_PrintFormat_ID,AD_Org_ID,XSpace,AD_PrintFont_ID,IsActive,IsHeightOneLine,MaxHeight,XPosition,FieldAlignmentType,IsPrinted,IsOrderBy,IsGroupBy,LineAlignmentType,PrintFormatType,PrintAreaType,ImageIsAttached,IsCounted,IsAveraged,IsSuppressNull,IsSetNLPosition,BelowColumn,IsNextPage,IsFixedWidth,IsMaxCalc,RunningTotalLines,IsRunningTotal,IsMinCalc,IsVarianceCalc,IsDeviationCalc,IsFilledRectangle,LineWidth,ArcDiameter,ShapeType,IsCentrallyMaintained,IsImageField,IsSuppressRepeats,AD_PrintFormatItem_UU,IsDesc) VALUES (10,'@Logo@',TO_TIMESTAMP('2019-09-30 11:54:40','YYYY-MM-DD HH24:MI:SS'),'N',0,0,0,214057,'N','N',100,100,200246,100,'N',0,100,TO_TIMESTAMP('2019-09-30 11:54:40','YYYY-MM-DD HH24:MI:SS'),200011,0,0,130,'Y','Y',60,0,'B','Y','N','N','X','I','H','N','N','N','N','N',0,'N','N','N',20,'N','N','N','N','N',1,0,'N','N','Y','N','02af2527-f5e7-43fa-aa5d-79ea737f3219','N')
;

-- Sep 30, 2019 12:09:16 PM IST
INSERT INTO AD_PrintFormatItem (SeqNo,Name,Created,IsNextLine,AD_Client_ID,YSpace,SortNo,IsPageBreak,IsRelativePosition,UpdatedBy,MaxWidth,AD_PrintFormatItem_ID,CreatedBy,IsSummarized,YPosition,Updated,AD_PrintFormat_ID,AD_Org_ID,XSpace,IsActive,IsHeightOneLine,MaxHeight,XPosition,FieldAlignmentType,IsPrinted,IsOrderBy,IsGroupBy,LineAlignmentType,PrintFormatType,PrintAreaType,ImageIsAttached,IsCounted,IsAveraged,IsSuppressNull,IsSetNLPosition,BelowColumn,IsNextPage,IsFixedWidth,IsMaxCalc,RunningTotalLines,IsRunningTotal,IsMinCalc,IsVarianceCalc,IsDeviationCalc,IsFilledRectangle,LineWidth,ArcDiameter,ShapeType,IsCentrallyMaintained,IsImageField,IsSuppressRepeats,AD_PrintFormatItem_UU,IsDesc) VALUES (20,'@Name@',TO_TIMESTAMP('2019-09-30 12:09:15','YYYY-MM-DD HH24:MI:SS'),'N',0,0,0,'N','N',100,325,200247,100,'N',0,TO_TIMESTAMP('2019-09-30 12:09:15','YYYY-MM-DD HH24:MI:SS'),200011,0,0,'Y','Y',0,100,'C','Y','N','N','X','T','H','N','N','N','N','N',0,'N','N','N',20,'N','N','N','N','N',1,0,'N','N','N','N','7b719586-b90d-46c8-b644-77cb5535d716','N')
;

-- Sep 30, 2019 12:14:20 PM IST
INSERT INTO AD_PrintFormatItem (SeqNo,Name,Created,IsNextLine,AD_Client_ID,PrintName,YSpace,SortNo,IsPageBreak,IsRelativePosition,UpdatedBy,MaxWidth,AD_PrintFormatItem_ID,CreatedBy,IsSummarized,YPosition,Updated,AD_PrintFormat_ID,AD_Org_ID,XSpace,AD_PrintFont_ID,IsActive,IsHeightOneLine,MaxHeight,XPosition,FieldAlignmentType,IsPrinted,IsOrderBy,IsGroupBy,LineAlignmentType,PrintFormatType,PrintAreaType,ImageIsAttached,IsCounted,IsAveraged,IsSuppressNull,IsSetNLPosition,BelowColumn,IsNextPage,IsFixedWidth,IsMaxCalc,RunningTotalLines,IsRunningTotal,IsMinCalc,IsVarianceCalc,IsDeviationCalc,IsFilledRectangle,LineWidth,ArcDiameter,ShapeType,IsCentrallyMaintained,IsImageField,IsSuppressRepeats,AD_PrintFormatItem_UU,IsDesc) VALUES (30,'Page Count',TO_TIMESTAMP('2019-09-30 12:14:19','YYYY-MM-DD HH24:MI:SS'),'N',0,'@Page@ @*Page@ @of@ @*PageCount@',0,0,'N','N',100,0,200248,100,'N',0,TO_TIMESTAMP('2019-09-30 12:14:19','YYYY-MM-DD HH24:MI:SS'),200011,0,0,133,'Y','Y',0,440,'T','Y','N','N','X','T','H','N','N','N','N','N',0,'N','N','N',20,'N','N','N','N','N',1,0,'N','N','N','N','a8b77290-ef83-428d-818b-eaf465fc86e9','N')
;

-- Sep 30, 2019 12:15:14 PM IST
INSERT INTO AD_PrintFormatItem (SeqNo,Name,Created,IsNextLine,AD_Client_ID,YSpace,SortNo,IsPageBreak,IsRelativePosition,UpdatedBy,MaxWidth,AD_PrintFormatItem_ID,CreatedBy,IsSummarized,YPosition,Updated,AD_PrintFormat_ID,AD_Org_ID,XSpace,IsActive,IsHeightOneLine,MaxHeight,XPosition,FieldAlignmentType,IsPrinted,IsOrderBy,IsGroupBy,LineAlignmentType,PrintFormatType,PrintAreaType,ImageIsAttached,IsCounted,IsAveraged,IsSuppressNull,IsSetNLPosition,BelowColumn,IsNextPage,IsFixedWidth,IsMaxCalc,RunningTotalLines,IsRunningTotal,IsMinCalc,IsVarianceCalc,IsDeviationCalc,IsFilledRectangle,LineWidth,ArcDiameter,ShapeType,IsCentrallyMaintained,IsImageField,IsSuppressRepeats,AD_PrintFormatItem_UU,IsDesc) VALUES (40,'@Client@',TO_TIMESTAMP('2019-09-30 12:15:13','YYYY-MM-DD HH24:MI:SS'),'Y',0,0,0,'N','Y',100,0,200249,100,'N',0,TO_TIMESTAMP('2019-09-30 12:15:13','YYYY-MM-DD HH24:MI:SS'),200011,0,0,'Y','Y',0,0,'D','Y','N','N','C','T','H','N','N','N','N','N',0,'N','N','N',20,'N','N','N','N','N',1,0,'N','N','N','N','d68d100a-2536-4749-bd45-1d9dbaf6da92','N')
;

-- Sep 30, 2019 12:15:48 PM IST
INSERT INTO AD_PrintFormatItem (SeqNo,Name,Created,IsNextLine,AD_Client_ID,YSpace,SortNo,IsPageBreak,IsRelativePosition,UpdatedBy,MaxWidth,AD_PrintFormatItem_ID,CreatedBy,IsSummarized,YPosition,Updated,AD_PrintFormat_ID,AD_Org_ID,XSpace,IsActive,IsHeightOneLine,MaxHeight,XPosition,FieldAlignmentType,IsPrinted,IsOrderBy,IsGroupBy,LineAlignmentType,PrintFormatType,PrintAreaType,ImageIsAttached,IsCounted,IsAveraged,IsSuppressNull,IsSetNLPosition,BelowColumn,IsNextPage,IsFixedWidth,IsMaxCalc,RunningTotalLines,IsRunningTotal,IsMinCalc,IsVarianceCalc,IsDeviationCalc,IsFilledRectangle,LineWidth,ArcDiameter,ShapeType,IsCentrallyMaintained,IsImageField,IsSuppressRepeats,AD_PrintFormatItem_UU,IsDesc) VALUES (50,'@Period@',TO_TIMESTAMP('2019-09-30 12:15:48','YYYY-MM-DD HH24:MI:SS'),'Y',0,0,0,'N','Y',100,0,200250,100,'N',0,TO_TIMESTAMP('2019-09-30 12:15:48','YYYY-MM-DD HH24:MI:SS'),200011,0,0,'Y','Y',0,0,'D','Y','N','N','C','T','H','N','N','N','N','N',0,'N','N','N',20,'N','N','N','N','N',1,0,'N','N','N','N','1be3dd4a-146a-4007-a3b0-983546f18e38','N')
;

-- Sep 30, 2019 12:16:29 PM IST
INSERT INTO AD_PrintFormatItem (SeqNo,Name,Created,IsNextLine,AD_Client_ID,YSpace,SortNo,IsPageBreak,IsRelativePosition,UpdatedBy,MaxWidth,AD_PrintFormatItem_ID,CreatedBy,IsSummarized,YPosition,Updated,AD_PrintFormat_ID,AD_Org_ID,XSpace,IsActive,IsHeightOneLine,MaxHeight,XPosition,FieldAlignmentType,IsPrinted,IsOrderBy,IsGroupBy,LineAlignmentType,PrintFormatType,PrintAreaType,ImageIsAttached,IsCounted,IsAveraged,IsSuppressNull,IsSetNLPosition,BelowColumn,IsNextPage,IsFixedWidth,IsMaxCalc,RunningTotalLines,IsRunningTotal,IsMinCalc,IsVarianceCalc,IsDeviationCalc,IsFilledRectangle,LineWidth,ArcDiameter,ShapeType,IsCentrallyMaintained,IsImageField,IsSuppressRepeats,AD_PrintFormatItem_UU,IsDesc) VALUES (60,'@Currency@',TO_TIMESTAMP('2019-09-30 12:16:28','YYYY-MM-DD HH24:MI:SS'),'Y',0,0,0,'N','Y',100,0,200251,100,'N',0,TO_TIMESTAMP('2019-09-30 12:16:28','YYYY-MM-DD HH24:MI:SS'),200011,0,0,'Y','Y',0,0,'D','Y','N','N','C','T','H','N','N','N','N','N',0,'N','N','N',20,'N','N','N','N','N',1,0,'N','N','N','N','f92b1a52-e4c3-4e94-b4d0-d1959d65e854','N')
;

-- Sep 30, 2019 12:18:06 PM IST
INSERT INTO AD_PrintFormatItem (SeqNo,Name,Created,IsNextLine,AD_Client_ID,YSpace,SortNo,AD_Column_ID,IsPageBreak,IsRelativePosition,UpdatedBy,MaxWidth,AD_PrintFormatItem_ID,CreatedBy,IsSummarized,YPosition,Updated,AD_PrintFormat_ID,AD_Org_ID,XSpace,IsActive,IsHeightOneLine,MaxHeight,XPosition,FieldAlignmentType,IsPrinted,IsOrderBy,IsGroupBy,LineAlignmentType,PrintFormatType,PrintAreaType,ImageIsAttached,IsCounted,IsAveraged,IsSuppressNull,IsSetNLPosition,BelowColumn,IsNextPage,IsFixedWidth,IsMaxCalc,RunningTotalLines,IsRunningTotal,IsMinCalc,IsVarianceCalc,IsDeviationCalc,IsFilledRectangle,LineWidth,ArcDiameter,ShapeType,IsCentrallyMaintained,IsImageField,IsSuppressRepeats,AD_PrintFormatItem_UU,IsDesc) VALUES (70,'Report',TO_TIMESTAMP('2019-09-30 12:18:06','YYYY-MM-DD HH24:MI:SS'),'N',0,0,0,2780,'N','N',100,0,200252,100,'N',0,TO_TIMESTAMP('2019-09-30 12:18:06','YYYY-MM-DD HH24:MI:SS'),200011,0,0,'Y','N',0,0,'D','Y','N','N','X','F','C','N','N','N','N','N',0,'N','N','N',20,'N','N','N','N','N',1,0,'N','N','N','N','17191c98-7032-44ea-8ff5-a37c438bdebf','N')
;

-- Sep 30, 2019 12:22:17 PM IST
INSERT INTO AD_PrintFormat (Updated,CreatedBy,IsTableBased,IsActive,IsStandardHeaderFooter,AD_PrintFont_ID,AD_Table_ID,IsForm,HeaderMargin,UpdatedBy,AD_PrintColor_ID,Created,Name,CreateCopy,FooterMargin,AD_Client_ID,AD_PrintPaper_ID,AD_Org_ID,AD_PrintFormat_ID,IsDefault,AD_PrintFormat_UU,RecordLimit) VALUES (TO_TIMESTAMP('2019-09-30 12:22:17','YYYY-MM-DD HH24:MI:SS'),100,'Y','Y','N',164,282,'Y',80,100,100,TO_TIMESTAMP('2019-09-30 12:22:17','YYYY-MM-DD HH24:MI:SS'),'Financial Report Header - Landscape','N',0,0,102,0,200012,'N','ef08d523-ef2b-4628-9ffa-7192d712b5ca',0)
;

-- Sep 30, 2019 12:22:58 PM IST
INSERT INTO AD_PrintFormatItem (SeqNo,Name,Created,IsNextLine,AD_Client_ID,YSpace,SortNo,AD_Column_ID,IsPageBreak,IsRelativePosition,UpdatedBy,MaxWidth,AD_PrintFormatItem_ID,CreatedBy,IsSummarized,YPosition,AD_PrintColor_ID,Updated,AD_PrintFormat_ID,AD_Org_ID,XSpace,AD_PrintFont_ID,IsActive,IsHeightOneLine,MaxHeight,XPosition,FieldAlignmentType,IsPrinted,IsOrderBy,IsGroupBy,LineAlignmentType,PrintFormatType,PrintAreaType,ImageIsAttached,IsCounted,IsAveraged,IsSuppressNull,IsSetNLPosition,BelowColumn,IsNextPage,IsFixedWidth,IsMaxCalc,RunningTotalLines,IsRunningTotal,IsMinCalc,IsVarianceCalc,IsDeviationCalc,IsFilledRectangle,LineWidth,ArcDiameter,ShapeType,IsCentrallyMaintained,IsImageField,IsSuppressRepeats,AD_PrintFormatItem_UU,IsDesc) VALUES (10,'@Logo@',TO_TIMESTAMP('2019-09-30 12:22:57','YYYY-MM-DD HH24:MI:SS'),'N',0,0,0,214057,'N','N',100,100,200253,100,'N',0,100,TO_TIMESTAMP('2019-09-30 12:22:57','YYYY-MM-DD HH24:MI:SS'),200012,0,0,130,'Y','Y',60,0,'B','Y','N','N','X','I','H','N','N','N','N','N',0,'N','N','N',20,'N','N','N','N','N',1,0,'N','N','Y','N','5c9b2f40-50a1-4e1a-b0eb-f6f540b5e698','N')
;

-- Sep 30, 2019 12:23:48 PM IST
INSERT INTO AD_PrintFormatItem (SeqNo,Name,Created,IsNextLine,AD_Client_ID,YSpace,SortNo,IsPageBreak,IsRelativePosition,UpdatedBy,MaxWidth,AD_PrintFormatItem_ID,CreatedBy,IsSummarized,YPosition,Updated,AD_PrintFormat_ID,AD_Org_ID,XSpace,IsActive,IsHeightOneLine,MaxHeight,XPosition,FieldAlignmentType,IsPrinted,IsOrderBy,IsGroupBy,LineAlignmentType,PrintFormatType,PrintAreaType,ImageIsAttached,IsCounted,IsAveraged,IsSuppressNull,IsSetNLPosition,BelowColumn,IsNextPage,IsFixedWidth,IsMaxCalc,RunningTotalLines,IsRunningTotal,IsMinCalc,IsVarianceCalc,IsDeviationCalc,IsFilledRectangle,LineWidth,ArcDiameter,ShapeType,IsCentrallyMaintained,IsImageField,IsSuppressRepeats,AD_PrintFormatItem_UU,IsDesc) VALUES (20,'@Name@',TO_TIMESTAMP('2019-09-30 12:23:47','YYYY-MM-DD HH24:MI:SS'),'N',0,0,0,'N','N',100,530,200254,100,'N',0,TO_TIMESTAMP('2019-09-30 12:23:47','YYYY-MM-DD HH24:MI:SS'),200012,0,0,'Y','Y',0,120,'C','Y','N','N','X','T','H','N','N','N','N','N',0,'N','N','N',20,'N','N','N','N','N',1,0,'N','N','N','N','db2840c7-940d-4904-854d-343bdcb675ee','N')
;

-- Sep 30, 2019 12:24:49 PM IST
INSERT INTO AD_PrintFormatItem (SeqNo,Name,Created,IsNextLine,AD_Client_ID,PrintName,YSpace,SortNo,IsPageBreak,IsRelativePosition,UpdatedBy,MaxWidth,AD_PrintFormatItem_ID,CreatedBy,IsSummarized,YPosition,Updated,AD_PrintFormat_ID,AD_Org_ID,XSpace,AD_PrintFont_ID,IsActive,IsHeightOneLine,MaxHeight,XPosition,FieldAlignmentType,IsPrinted,IsOrderBy,IsGroupBy,LineAlignmentType,PrintFormatType,PrintAreaType,ImageIsAttached,IsCounted,IsAveraged,IsSuppressNull,IsSetNLPosition,BelowColumn,IsNextPage,IsFixedWidth,IsMaxCalc,RunningTotalLines,IsRunningTotal,IsMinCalc,IsVarianceCalc,IsDeviationCalc,IsFilledRectangle,LineWidth,ArcDiameter,ShapeType,IsCentrallyMaintained,IsImageField,IsSuppressRepeats,AD_PrintFormatItem_UU,IsDesc) VALUES (30,'Page Count',TO_TIMESTAMP('2019-09-30 12:24:48','YYYY-MM-DD HH24:MI:SS'),'N',0,'@Page@ @*Page@ @of@ @*PageCount@',0,0,'N','N',100,115,200255,100,'N',0,TO_TIMESTAMP('2019-09-30 12:24:48','YYYY-MM-DD HH24:MI:SS'),200012,0,0,133,'Y','Y',0,650,'T','Y','N','N','X','T','H','N','N','N','N','N',0,'N','N','N',20,'N','N','N','N','N',1,0,'N','N','N','N','7883c180-baa3-4316-8016-ba5b624472d8','N')
;

-- Sep 30, 2019 12:25:25 PM IST
INSERT INTO AD_PrintFormatItem (SeqNo,Name,Created,IsNextLine,AD_Client_ID,YSpace,SortNo,IsPageBreak,IsRelativePosition,UpdatedBy,MaxWidth,AD_PrintFormatItem_ID,CreatedBy,IsSummarized,YPosition,Updated,AD_PrintFormat_ID,AD_Org_ID,XSpace,IsActive,IsHeightOneLine,MaxHeight,XPosition,FieldAlignmentType,IsPrinted,IsOrderBy,IsGroupBy,LineAlignmentType,PrintFormatType,PrintAreaType,ImageIsAttached,IsCounted,IsAveraged,IsSuppressNull,IsSetNLPosition,BelowColumn,IsNextPage,IsFixedWidth,IsMaxCalc,RunningTotalLines,IsRunningTotal,IsMinCalc,IsVarianceCalc,IsDeviationCalc,IsFilledRectangle,LineWidth,ArcDiameter,ShapeType,IsCentrallyMaintained,IsImageField,IsSuppressRepeats,AD_PrintFormatItem_UU,IsDesc) VALUES (40,'@Client@',TO_TIMESTAMP('2019-09-30 12:25:24','YYYY-MM-DD HH24:MI:SS'),'Y',0,0,0,'N','Y',100,0,200256,100,'N',0,TO_TIMESTAMP('2019-09-30 12:25:24','YYYY-MM-DD HH24:MI:SS'),200012,0,0,'Y','Y',0,0,'D','Y','N','N','C','T','H','N','N','N','N','N',0,'N','N','N',20,'N','N','N','N','N',1,0,'N','N','N','N','fc6a9d59-c027-4547-98c3-9082cf7bf331','N')
;

-- Sep 30, 2019 12:25:52 PM IST
INSERT INTO AD_PrintFormatItem (SeqNo,Name,Created,IsNextLine,AD_Client_ID,YSpace,SortNo,IsPageBreak,IsRelativePosition,UpdatedBy,MaxWidth,AD_PrintFormatItem_ID,CreatedBy,IsSummarized,YPosition,Updated,AD_PrintFormat_ID,AD_Org_ID,XSpace,IsActive,IsHeightOneLine,MaxHeight,XPosition,FieldAlignmentType,IsPrinted,IsOrderBy,IsGroupBy,LineAlignmentType,PrintFormatType,PrintAreaType,ImageIsAttached,IsCounted,IsAveraged,IsSuppressNull,IsSetNLPosition,BelowColumn,IsNextPage,IsFixedWidth,IsMaxCalc,RunningTotalLines,IsRunningTotal,IsMinCalc,IsVarianceCalc,IsDeviationCalc,IsFilledRectangle,LineWidth,ArcDiameter,ShapeType,IsCentrallyMaintained,IsImageField,IsSuppressRepeats,AD_PrintFormatItem_UU,IsDesc) VALUES (50,'@Period@',TO_TIMESTAMP('2019-09-30 12:25:51','YYYY-MM-DD HH24:MI:SS'),'Y',0,0,0,'N','Y',100,0,200257,100,'N',0,TO_TIMESTAMP('2019-09-30 12:25:51','YYYY-MM-DD HH24:MI:SS'),200012,0,0,'Y','Y',0,0,'D','Y','N','N','C','T','H','N','N','N','N','N',0,'N','N','N',20,'N','N','N','N','N',1,0,'N','N','N','N','6268fe6c-b045-43bd-a815-9f5676a62b9c','N')
;

-- Sep 30, 2019 12:26:18 PM IST
INSERT INTO AD_PrintFormatItem (SeqNo,Name,Created,IsNextLine,AD_Client_ID,YSpace,SortNo,IsPageBreak,IsRelativePosition,UpdatedBy,MaxWidth,AD_PrintFormatItem_ID,CreatedBy,IsSummarized,YPosition,Updated,AD_PrintFormat_ID,AD_Org_ID,XSpace,IsActive,IsHeightOneLine,MaxHeight,XPosition,FieldAlignmentType,IsPrinted,IsOrderBy,IsGroupBy,LineAlignmentType,PrintFormatType,PrintAreaType,ImageIsAttached,IsCounted,IsAveraged,IsSuppressNull,IsSetNLPosition,BelowColumn,IsNextPage,IsFixedWidth,IsMaxCalc,RunningTotalLines,IsRunningTotal,IsMinCalc,IsVarianceCalc,IsDeviationCalc,IsFilledRectangle,LineWidth,ArcDiameter,ShapeType,IsCentrallyMaintained,IsImageField,IsSuppressRepeats,AD_PrintFormatItem_UU,IsDesc) VALUES (60,'@Currency@',TO_TIMESTAMP('2019-09-30 12:26:17','YYYY-MM-DD HH24:MI:SS'),'Y',0,0,0,'N','Y',100,0,200258,100,'N',0,TO_TIMESTAMP('2019-09-30 12:26:17','YYYY-MM-DD HH24:MI:SS'),200012,0,0,'Y','Y',0,0,'D','Y','N','N','C','T','H','N','N','N','N','N',0,'N','N','N',20,'N','N','N','N','N',1,0,'N','N','N','N','61e1e09e-662f-439d-a286-50fa90c231ad','N')
;

-- Sep 30, 2019 12:27:05 PM IST
INSERT INTO AD_PrintFormatItem (SeqNo,Name,Created,IsNextLine,AD_Client_ID,YSpace,SortNo,AD_Column_ID,IsPageBreak,IsRelativePosition,UpdatedBy,MaxWidth,AD_PrintFormatItem_ID,CreatedBy,IsSummarized,YPosition,Updated,AD_PrintFormat_ID,AD_Org_ID,XSpace,IsActive,IsHeightOneLine,MaxHeight,XPosition,FieldAlignmentType,IsPrinted,IsOrderBy,IsGroupBy,LineAlignmentType,PrintFormatType,PrintAreaType,ImageIsAttached,IsCounted,IsAveraged,IsSuppressNull,IsSetNLPosition,BelowColumn,IsNextPage,IsFixedWidth,IsMaxCalc,RunningTotalLines,IsRunningTotal,IsMinCalc,IsVarianceCalc,IsDeviationCalc,IsFilledRectangle,LineWidth,ArcDiameter,ShapeType,IsCentrallyMaintained,IsImageField,IsSuppressRepeats,AD_PrintFormatItem_UU,IsDesc) VALUES (70,'Report',TO_TIMESTAMP('2019-09-30 12:27:05','YYYY-MM-DD HH24:MI:SS'),'N',0,0,0,2780,'N','N',100,0,200259,100,'N',0,TO_TIMESTAMP('2019-09-30 12:27:05','YYYY-MM-DD HH24:MI:SS'),200012,0,0,'Y','Y',0,0,'D','Y','N','N','X','F','C','N','N','N','N','N',0,'N','N','N',20,'N','N','N','N','N',1,0,'N','N','N','N','9414beb4-4468-46eb-a957-dcf9f0a371db','N')
;

-- Sep 30, 2019 12:36:32 PM IST
UPDATE AD_PrintFormatItem SET AD_PrintFormatChild_ID=NULL, YSpace=0, SortNo=0, IsPageBreak='N', XSpace=0, IsGroupBy='N', PrintFormatType='P',Updated=TO_TIMESTAMP('2019-09-30 12:36:32','YYYY-MM-DD HH24:MI:SS'),UpdatedBy=100 WHERE AD_PrintFormatItem_ID=200252
;

-- Sep 30, 2019 12:36:45 PM IST
UPDATE AD_PrintFormatItem SET AD_PrintFormatChild_ID=NULL, YSpace=0, SortNo=0, IsPageBreak='N', XSpace=0, IsGroupBy='N', PrintFormatType='P',Updated=TO_TIMESTAMP('2019-09-30 12:36:45','YYYY-MM-DD HH24:MI:SS'),UpdatedBy=100 WHERE AD_PrintFormatItem_ID=200259
;

SELECT register_migration_script('201909301245_Financial_Report_Header_Print_Format.sql') FROM dual
;